inputs/all.json
inputs/blosc.json
src/compressors/BLOSC/blosccompressor.hpp
src/compressors/BigCrunch/BigCrunchcompressor.hpp
src/compressors/SZ/SZcompressor.hpp
src/compressors/compressorInterface.hpp
src/dataLoader/dataLoaderInterface.hpp
src/main.cpp
src/metrics/absoluteError.hpp
src/metrics/meansquareError.hpp
src/metrics/metricInterface.hpp
src/metrics/relativeError.hpp
src/utils/strConvert.hpp
tutorial/AddingCompressors.md
tutorial/zfp_tutorial_files/main_modifications.diff
tutorial/zfp_tutorial_files/zfp_CMakeListsAddition.txt

Added compression ratio as metric, fix reduces, ...

Pre first release

---

.travis.yml
README.md
testing/travis/README.md

Adds documentation for building Docker image for Travis CI.

Add some instructions for building Docker image for Travis CI

---

src/compressors/SZ/SZcompressor.hpp

Test PR for merging with `master-dev-II`.

Include lower and upper absolute bounds.

---

analysisWorkflow/raw_output_test.py
buildAll.sh
inputs/HACC_all_v1.json
inputs/darwin_step499_fpzip_isabela_zfp_sz_BC.json
inputs/darwin_step499_fpzip_v1.json
scripts/runJob.darwin.HACC_499__fpzip_isabela_BC_SZ_ZFP.sh
src/compressors/SZ/SZcompressor.hpp
src/compressors/compressorFactory.hpp
src/compressors/compressorInterface.hpp
src/compressors/fpzip/fpzipcompressor.hpp
src/main.cpp
src/metrics/absoluteError.hpp
src/metrics/metricInterface.hpp
tools/plotting/plotHistogram.py

Master dev ii

---

inputs/HACC_all.json
src/compressors/Isabela/Isabelacompressor.hpp

This PR allows the window size setting in Isabela's configuration to be changed.

Alter window size for Isabela

---

.gitignore
analysisWorkflow/readme.md
analysisWorkflow/workflow_c.ini
analysisWorkflow/workflow_c.py

This adds a ``analysisWorkflow/workflow_c.py`` which connects the full analysis pipeline. There is a configuration file also, located `analysisWorkflow/workflow_c.ini`.
In subsequent PR, I will add plotting jobs.
Work in progress.

Connect CBench, Halo Finder, and Spectra in a single workflow

---

analysisWorkflow/readme.md
analysisWorkflow/workflow_c.ini
analysisWorkflow/workflow_c.py

Includes input file to CBench in halo finding and spectra analysis. Adds documentation and comments.

Include input file in analysis of workflow

---

analysisWorkflow/plot_halo_distribution.py
analysisWorkflow/plot_spectrum.py
analysisWorkflow/workflow_c.py

Adds two plotting executables for plotting SQL queries on halo finder output and spectra.

Add plotting executables for spectra and halo queries

---

analysisWorkflow/workflow_c.py

As title says. Writes parsed configuration for workflow.

Add command line overrides for configuration file

---

analysisWorkflow/workflow_c.py

Add if statement to overrides

---

analysisWorkflow/create_cinema.py
analysisWorkflow/plot_gio_distribution.py

Adds difference and absolute difference between histograms to plotting executable.

Add more plotting options to histogram executable

---

.travis.yml
testing/travis/Dockerfile
testing/travis/test_build.sh
tools/externalDependencies/build_SZ.sh

Updates SZ to v2.1.1 and adds OpenCL to TravisCI since the latest version requires it.

Update SZ to v2.1.1 and add OpenCL to TravisCI

---

scripts/nyx-tests.sh
src/CMakeLists.txt

Fixes the HDF5 library linking issue.

Fix HDF5 library linking issue

---

build_macOS.sh
src/CMakeLists.txt
src/compressors/SZ/SZcompressor.hpp
src/utils/memory.hpp

A patch which enables to build CBench natively on macOS.

Enable to build natively on macOS

---

CBench/dataLoader/NYX/NYXDataLoader.hpp
CBench/utils/memory.hpp

This fixes the uncompressed attribute memory allocation failure.
Tested on the main repo in Darwin using `nyx_thermal_512_all.json`.

Fix group attribute memory allocation failure

---

testing/travis/Dockerfile

Yum install hdf5-openmpi in DockerFile

---

.travis.yml
build.sh
buildDependencies.sh
testing/travis/test_build.sh
tools/externalDependencies/build_HDF5.sh

Use system installed HDF5 for TravisCI

---

CBench/CMakeLists.txt
CBench/compressors/BLOSC/CMakeLists.txt
CBench/compressors/BigCrunch/CMakeLists.txt
CBench/compressors/Isabela/CMakeLists.txt
CBench/compressors/LossyWave/CMakeLists.txt
CBench/compressors/MGARD/CMakeLists.txt
CBench/compressors/SZ/CMakeLists.txt
CBench/compressors/fpzip/CMakeLists.txt
CBench/compressors/zfp/CMakeLists.txt
CBench/main.cpp
testing/travis/test_build.sh

Master for cori

---

Analysis/README.md

Fixes some typos.
Also, there's a `requirements.txt` file that specifies the Python packages and versions that should be installed. I reference this here.

Improve README for PAT

---

Analysis/README.md
inputs/hacc/hacc_wflow.json

As title says. Minor changes to example to match new organization of information.

Conform to new workflow configuration for HACC example.

---

Analysis/HACC_Analysis_readme.md
Analysis/pat/cinema.py
Analysis/pat/workflow.py
Analysis/pat_cinema.py
Analysis/pat_hacc.py
Analysis/pat_hacc_query.py
CBench/main.cpp
inputs/hacc/hacc_wflow.json
testing/travis/test_build.sh

Adds a job that writes a CSV of the halo distribution, and a job that creates a Cinema database.
Work in progress. Do not merge yet.

Add visualizations to HACC workflow

---

Analysis/pat_cinema.py
inputs/hacc/hacc_wflow.json

Adds some sections to ``cinema-plots`` that get read for formatting.

Add formatting to plots in HACC workflow

---

Analysis/pat/workflow.py
inputs/hacc/hacc_wflow.json

Updates paths in the configuration file to run the workflow outside the Git repository.

Run HACC workflow outside Git repository

---

.travis.yml
testing/travis/Dockerfile
testing/travis/test_build.sh

Updates the `Dockerfile` and the Travis CI test for `python3`. Do not merge.

Update Dockerfile and TravisCI for python3.

---

Analysis/setup.py

Fix email in Python package

---

Analysis/pat/hacc/hacc_cinema.py
Analysis/pat/hacc/pat_hacc.py
Analysis/pat/vpic/pat_vpic.py
Analysis/setup.py
build.sh
inputs/vpic/vpic_wflow.json

A simple workflow generator for VPIC.

Simple VPIC workflow generator

---

.travis.yml
testing/travis/Dockerfile

Update CMake to 3.14.0 for CI tests.

---

README.md

Diff should be self-explanatory.

Fix minor typos in README.
